version: '3.8'
services:
  java:
    tty: true
    build:
      context: ../
      dockerfile: app.dockerfile
      args:
        - APP_ENV=local
        - PORT=${PORT}
        - PORT_DEBUG=${PORT_DEBUG}
        - GITHUB_ACTOR=${GITHUB_ACTOR:-}
        - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    restart: always
    container_name: general_java_app_template
    ports:
      - "${PORT}:${PORT}"
      - "${PORT_DEBUG}:${PORT_DEBUG}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/home
    networks:
      - main_network
networks:
  main_network:
    driver: bridge
