version: '3.8'
services:
  java:
    tty: true
    build:
      context: ../
      dockerfile: app.dockerfile
      args:
        - APP_ENV=local
        - PORT=${PORT}
        - GITHUB_SERVER_USER=${GITHUB_SERVER_USER}
        - GITHUB_SERVER_PASSWORD=${GITHUB_SERVER_PASSWORD}
    restart: always
    container_name: general_java_app_template
    ports:
      - "${PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../app:/home/app
    networks:
      - main_network
networks:
  main_network:
    driver: bridge
