server:
  port: 8081
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: ["health"]
        exclude: ["prometheus", "autoconfig", "beans", "configprops", "dump", "env", "metrics", "mappings", "shutdown", "trace"]
      base-path: /
      path-mapping:
        health: /health-check

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  devtools:
    remote:
      secret: local
    restart:
      enabled: true
