name: Build and Deploy to GCP - PROD
on:
  push:
    branches: main
jobs:
  ci-cd:
    name: CI/CD
    uses: felipemenezesdm/general-deploy-actions/.github/workflows/gcp-spring-app-prod.yml@v1
    secrets: inherit
    with:
      service: ${{ github.event.repository.name }}
      sha: ${{ github.sha }}
